[package]
edition = "2018"
name = "example"
version = "0.0.0"

[dependencies]
argh = "0.1.3"
async-std = { version = "1.5.0", features = ["attributes", "unstable"] }
derive_more = "0.99.2"
env_logger = "0.7.1"
futures = "0.3.4"
itertools = "0.8.2"
log = "0.4.8"
no-panic = "0.1.12"
rand = "0.7.3"
