[package]
edition = "2018"
license = "MIT"
name = "example"
version = "0.0.1"

default-run = "serve"

[lib]
name = "speedruns"

[[bin]]
name = "serve"

[dependencies]
derive_more = "0.99.2"
env_logger = "0.7.1"
err-derive = "0.1.5"
flate2 = "1.0.13"
fs2 = "0.4.0"
getset = "0.0.9"
itertools = "0.8.2"
juniper = "0.14.2"
juniper-from-schema = "0.5.1"
lazy_static = "1.4.0"
log = "0.4.8"
no-panic = "0.1.12"
percent-encoding = "2.1.0"
pretty_env_logger = "0.3.1"
regex = "1.3.3"
remain = "0.2.1"
reqwest = "0.9.24"
serde_derive = "1.0.0"
serde_json = "1.0.45"
sha2 = "0.8.0"
tempfile = "3.1.0"
unidecode = "0.3.0"
url_serde = "0.2.0"
validator = "0.10.0"
validator_derive = "0.10.0"
base64 = "0.11.0"
arrayvec = "0.5.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4.10"

[dependencies.serde]
features = ["derive"]
version = "1.0.104"

[dependencies.url]
features = ["serde"]
version = "2.1.1"
