[package]
name = "mandelbrot"
edition = "2018"
publish = false
license = "MIT"
version = "0.0.1"

[dependencies]
bincode = "1.1.3"
derive_more = "0.14.0"
env_logger = "0.6.1"
err-derive = "0.1.5"
getset = "0.0.7"
itertools = "0.8.0"
log = "0.4.6"
regex = "1.1.6"
tempfile = "3.0.7"
image = "0.21.1"

[dependencies.rug]
version = "1.4.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.90"
features = ["derive"]
