name: Actions
on: [push]

jobs:
  my-job:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - name: preparation - checkout source
        uses: actions/checkout@v1

      - name: setup - install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo run
        uses: actions-rs/cargo@v1
        with:
          command: run
        env:
          RUST_BACKTRACE: full
          JUNIPER_FROM_SCHEMA_DEBUG: 1
